// Konten legal & informasi aplikasi INDOMINE

export const APP_VERSION = '1.0.0';
export const APP_NAME = 'INDOMINE';
export const DEVELOPER = 'ALTOMEDIA';
export const ADMIN_EMAIL = 'altomediaindonesia@gmail.com';
export const PLAYSTORE_URL = 'https://play.google.com/store/apps/details?id=com.altomedia.indomine';
export const WA_CHANNEL_URL = 'https://whatsapp.com/channel/0029VbDlYg9HVvTbH0KDRg0R';

export const DISCLAIMER_TEXT = [
  'DISCLAIMER — INDOMINE',
  '',
  'Terakhir diperbarui: 2026',
  '',
  'Selamat datang di INDOMINE, aplikasi permainan simulasi penambangan idle yang dikembangkan oleh ALTOMEDIA. Dengan mengunduh, menginstal, mengakses, atau menggunakan aplikasi ini, Anda dianggap telah membaca, memahami, dan menyetujui seluruh isi disclaimer berikut.',
  '',
  '1. SIFAT PERMAINAN',
  'INDOMINE adalah permainan simulasi penambangan virtual yang dirancang untuk tujuan hiburan semata. Seluruh aktivitas penambangan di dalam aplikasi — termasuk koin, peralatan tambang, pekerja, conveyor, dan area tambang — adalah elemen virtual dalam permainan dan tidak merepresentasikan aktivitas penambangan nyata, kepemilikan aset fisik, maupun investasi dalam bentuk apa pun.',
  '',
  '2. KOIN VIRTUAL',
  'Koin yang diperoleh di dalam aplikasi merupakan mata uang virtual dalam permainan. Nilai tukar, konversi, dan fitur penarikan yang tersedia di dalam aplikasi tunduk pada syarat dan ketentuan yang berlaku serta kebijakan yang ditetapkan oleh pengembang. Pengembang berhak mengubah nilai, syarat, dan ketentuan koin virtual sewaktu-waktu dengan pemberitahuan melalui aplikasi.',
  '',
  '3. KETENTUAN PENARIKAN',
  'Fitur penarikan saldo tunduk pada persyaratan tertentu yang ditetapkan oleh pengembang, termasuk namun tidak terbatas pada pemenuhan aktivitas minimum di dalam aplikasi. Permintaan penarikan akan diverifikasi oleh tim kami sebelum diproses. Pengembang berhak menolak permintaan penarikan yang terindikasi melanggar ketentuan, menggunakan kecurangan, bot, eksploitasi bug, atau aktivitas tidak wajar lainnya.',
  '',
  '4. KEWAJIBAN PENGGUNA',
  'Pengguna wajib menggunakan aplikasi secara wajar dan bertanggung jawab. Dilarang keras melakukan rekayasa balik (reverse engineering), modifikasi aplikasi, penggunaan skrip otomatis, pembuatan banyak akun untuk penyalahgunaan sistem referral, maupun tindakan lain yang merugikan pengembang atau pengguna lain. Pelanggaran terhadap ketentuan ini dapat mengakibatkan pembekuan saldo, penangguhan akun, atau penghapusan akun secara permanen.',
  '',
  '5. KETERSEDIAAN LAYANAN',
  'Aplikasi ini memerlukan koneksi internet untuk berfungsi. Pengembang berupaya menjaga ketersediaan layanan namun tidak menjamin layanan bebas dari gangguan, pemeliharaan terjadwal, atau keadaan kahar. Pengembang tidak bertanggung jawab atas kerugian yang timbul akibat gangguan layanan di luar kendali kami.',
  '',
  '6. BATASAN TANGGUNG JAWAB',
  'Aplikasi disediakan "sebagaimana adanya" tanpa jaminan dalam bentuk apa pun, baik tersurat maupun tersirat. Sejauh diizinkan oleh hukum yang berlaku, ALTOMEDIA tidak bertanggung jawab atas kerugian langsung maupun tidak langsung yang timbul dari penggunaan atau ketidakmampuan menggunakan aplikasi ini.',
  '',
  '7. PERUBAHAN DISCLAIMER',
  'Pengembang berhak mengubah isi disclaimer ini sewaktu-waktu. Versi terbaru akan selalu tersedia di dalam aplikasi. Penggunaan berkelanjutan atas aplikasi setelah perubahan dianggap sebagai persetujuan terhadap disclaimer yang diperbarui.',
  '',
  '8. HUKUM YANG BERLAKU',
  'Disclaimer ini diatur oleh dan ditafsirkan sesuai dengan hukum Republik Indonesia. Segala perselisihan yang timbul akan diselesaikan terlebih dahulu secara musyawarah.',
  '',
  'Dengan menggunakan INDOMINE, Anda menyatakan telah membaca dan menyetujui seluruh ketentuan di atas.',
].join('\n');

export const PRIVACY_POLICY_TEXT = [
  'KEBIJAKAN PRIVASI — INDOMINE',
  '',
  'Terakhir diperbarui: 2026',
  '',
  'ALTOMEDIA ("kami", "pengembang") menghargai privasi Anda. Kebijakan Privasi ini menjelaskan bagaimana kami mengumpulkan, menggunakan, menyimpan, dan melindungi informasi Anda saat menggunakan aplikasi INDOMINE.',
  '',
  '1. INFORMASI YANG KAMI KUMPULKAN',
  'a) Data Akun: Saat mendaftar, kami mengumpulkan username, nomor telepon, dan kata sandi (tersimpan dalam bentuk terenkripsi oleh sistem autentikasi kami).',
  'b) Data Permainan: Kami menyimpan progres permainan Anda — jumlah koin, level, riwayat upgrade, misi harian, streak check-in, dan riwayat transaksi — agar progres Anda tidak hilang saat berganti perangkat.',
  'c) Data Referral: Kode referral milik Anda dan informasi siapa yang mengundang Anda, untuk keperluan perhitungan bonus referral.',
  'd) Data Teknis: Informasi perangkat seperti model, versi sistem operasi, dan pengidentifikasi teknis yang diperlukan untuk kestabilan aplikasi dan penyelesaian masalah.',
  '',
  '2. CARA KAMI MENGGUNAKAN INFORMASI',
  'Informasi yang dikumpulkan digunakan untuk:',
  '- Membuat dan mengelola akun Anda;',
  '- Menyimpan dan menyinkronkan progres permainan di seluruh perangkat;',
  '- Memverifikasi permintaan penarikan saldo;',
  '- Menghitung dan mendistribusikan bonus referral dan bonus pendaftaran;',
  '- Mencegah kecurangan, penyalahgunaan, dan aktivitas yang melanggar ketentuan;',
  '- Menghubungi Anda terkait layanan, pembaruan, atau masalah akun;',
  '- Meningkatkan kualitas, kinerja, dan keamanan aplikasi.',
  '',
  '3. PENYIMPANAN DATA',
  'Data Anda disimpan pada infrastruktur cloud yang aman. Kami menerapkan langkah-langkah teknis dan organisasi yang wajar untuk melindungi data dari akses tidak sah, kehilangan, atau penyalahgunaan. Data disimpan selama akun Anda aktif atau selama diperlukan untuk memenuhi tujuan yang dijelaskan dalam kebijakan ini.',
  '',
  '4. BERBAGI INFORMASI',
  'Kami TIDAK menjual data pribadi Anda kepada pihak ketiga. Informasi hanya dapat dibagikan dalam kondisi berikut:',
  '- Kepada penyedia layanan infrastruktur (hosting cloud, autentikasi) yang membantu operasional aplikasi, dengan kewajiban perlindungan data yang setara;',
  '- Apabila diwajibkan oleh hukum, peraturan, proses hukum, atau permintaan resmi pemerintah yang sah;',
  '- Untuk melindungi hak, properti, atau keselamatan pengembang, pengguna, atau publik.',
  '',
  '5. KEAMANAN AKUN',
  'Anda bertanggung jawab menjaga kerahasiaan kata sandi dan nomor telepon yang terdaftar. Segera hubungi kami apabila Anda mencurigai adanya akses tidak sah ke akun Anda. Kami tidak pernah meminta kata sandi Anda melalui telepon, pesan singkat, atau media sosial.',
  '',
  '6. HAK PENGGUNA',
  'Anda berhak untuk:',
  '- Mengakses dan memperbarui data profil Anda;',
  '- Meminta penghapusan akun beserta data yang terkait, dengan konsekuensi seluruh progres, koin, dan riwayat akan dihapus permanen dan tidak dapat dipulihkan;',
  '- Mengajukan pertanyaan atau keluhan terkait privasi melalui kontak yang tersedia.',
  '',
  '7. ANAK-ANAK',
  'Aplikasi ini tidak ditujukan untuk anak di bawah 13 tahun. Kami tidak dengan sengaja mengumpulkan data pribadi anak-anak. Apabila Anda mengetahui adanya anak di bawah umur yang memberikan data kepada kami, silakan hubungi kami agar data tersebut dapat dihapus.',
  '',
  '8. TAUTAN PIHAK KETIGA',
  'Aplikasi dapat memuat tautan ke layanan pihak ketiga seperti Google Play Store dan WhatsApp. Kami tidak bertanggung jawab atas kebijakan privasi layanan pihak ketiga tersebut. Kami menyarankan Anda membaca kebijakan privasi masing-masing layanan.',
  '',
  '9. PERUBAHAN KEBIJAKAN',
  'Kami dapat memperbarui Kebijakan Privasi ini dari waktu ke waktu. Versi terbaru selalu tersedia di dalam aplikasi. Perubahan material akan diumumkan melalui aplikasi sebelum diberlakukan.',
  '',
  '10. HUBUNGI KAMI',
  'Untuk pertanyaan, permintaan, atau keluhan terkait privasi, hubungi:',
  'Email: altomediaindonesia@gmail.com',
  'Developer: ALTOMEDIA — Indonesia',
].join('\n');

export const ABOUT_TEXT = [
  'TENTANG APLIKASI — INDOMINE',
  '',
  `Versi: ${APP_VERSION}`,
  `Developer: ${DEVELOPER}`,
  `Kontak Admin: ${ADMIN_EMAIL}`,
  '',
  'INDOMINE adalah permainan idle mining buatan Indonesia yang mengajak Anda membangun kerajaan tambang virtual dari nol. Mulai dari tambang batu sederhana, tingkatkan peralatan, rekrut pekerja, percepat produksi, dan buka area tambang baru yang semakin bernilai — hingga ke kedalaman berlian!',
  '',
  'FITUR UTAMA',
  '• Penambangan Otomatis: Mesin tambang terus bekerja mengumpulkan koin untuk Anda, bahkan saat Anda sedang tidak bermain.',
  '• Sistem Upgrade: Tingkatkan Pickaxe, Mining Speed, Worker, Storage, dan Conveyor untuk melipatgandakan hasil tambang.',
  '• Area Tambang Bertingkat: Buka Stone Valley, Iron Cave, Gold Mountain, Crystal Cavern, hingga Diamond Depths dengan pengganda hasil yang semakin besar.',
  '• Misi Harian: Selesaikan misi setiap hari — menambang koin, melakukan upgrade, check-in harian, dan mengundang teman — untuk mendapatkan bonus koin melimpah.',
  '• Daily Reward Streak: Masuk setiap hari untuk klaim hadiah harian dengan streak yang terus naik hingga hari ke-7.',
  '• Sistem Referral: Bagikan kode referral Anda. Setiap teman yang bergabung dengan kode Anda memberikan bonus 250 koin untuk Anda DAN 250 koin untuk teman Anda.',
  '• Bonus Pendaftaran: Pengguna baru langsung mendapatkan 200 koin gratis untuk memulai petualangan.',
  '• Level & XP: Kumpulkan XP dari aktivitas bermain dan naikkan level penambang Anda.',
  '• Status VIP: Tingkatkan status VIP untuk bonus hasil tambang eksklusif.',
  '• Dompet & Penarikan: Kumpulkan koin dan tukarkan menjadi saldo sesuai syarat dan ketentuan yang berlaku.',
  '• Sinkronisasi Cloud: Progres Anda tersimpan aman di cloud — ganti perangkat tanpa kehilangan apa pun.',
  '',
  'CARA BERMAIN',
  '1. Daftarkan akun dengan nomor telepon Anda.',
  '2. Biarkan mesin menambang koin secara otomatis.',
  '3. Kumpulkan koin dan upgrade peralatan tambang.',
  '4. Selesaikan misi harian dan klaim hadiah.',
  '5. Undang teman dengan kode referral untuk bonus bersama.',
  '6. Buka area tambang baru dan maksimalkan produksi.',
  '7. Penuhi syarat penarikan dan cairkan hasil kerja kerasmu.',
  '',
  'PENGEMBANG',
  'INDOMINE dikembangkan dan dikelola oleh ALTOMEDIA, pengembang aplikasi asal Indonesia yang berkomitmen menghadirkan hiburan berkualitas dengan nilai lebih bagi penggunanya.',
  '',
  'HUBUNGI KAMI',
  'Punya pertanyaan, saran, atau menemukan kendala? Tim kami siap membantu:',
  `Email: ${ADMIN_EMAIL}`,
  'Channel WhatsApp resmi kami tersedia di halaman Profil.',
  '',
  'Terima kasih telah bermain INDOMINE. Selamat menambang!',
].join('\n');
