packages:
  - "."

allowBuilds:
  '@firebase/util': false
  protobufjs: false
  react-native-elements: false
  unrs-resolver: false

patchedDependencies:
  react-native-google-mobile-ads: patches/react-native-google-mobile-ads.patch
